/*
 * Generated by MTK Drv_CodeGen Version 04.08.0 for MT6575_NP. Copyright MediaTek Inc. (C) 2011.
 * Tue Oct 15 11:28:52 2013
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


